#!/bin/bash

confirm() {
  read -p "$1? (y/N) : " -n 1 -e rep ; if [ "$rep" = "y" ] ; then true ; else if [ \! -z "$exit_message" ] ; then echo -e "$exit_message" ; exit 1 ; fi ; false ; fi
}

# Usage: Installs a RasPi-like light environment on Ubuntu or other Linux distributions

## Manually defines the most recent theme and icons
## - Note: This was set on 2026/09/29 and may/will evolve with time

theme=pix-theme_0.1_amd64
icons=pixtrix-icons_0.6_all+debcompat

## Installs the RasPi-like light environment at the system level

if confirm "Install the PIXEL themes and icons ?" "Ok, bye"
then
  ### 0/ Works in a temporary directory
  /bin/rm -rf /tmp/install*
  mkdir -p /tmp/install$$
  pushd /tmp/install$$ >/dev/null

  ### 1/ Installs lxqt if not yet done
  sudo apt install -qq -y lxqt

  ### 2/ Installs the PiX theme
  wget -q https://github.com/b1ack0p/pixflat-theme/raw/main/packages/pool/themes/$theme.deb
  dpkg-deb -R $theme.deb .
  sudo cp -r usr/share/themes/PiX /usr/share/themes
  /bin/rm -rf DEBIAN usr

  ### 3/ Installs PiX icons
  wget -q https://github.com/b1ack0p/pixflat-theme/raw/main/packages/pool/icons/$icons.deb
  dpkg-deb -R $icons.deb .
  sudo cp -r usr/share/icons/PiX* /usr/share/icons

  ### 00/ Cleans up
  popd >/dev/null
  /bin/rm -rf /tmp/install*
fi

