[general]
fontname=Monospace 16
selchars=-A-Za-z0-9,./?%&#:_
scrollback=1000
boldbright=true
bgcolor=rgb(0,0,0)
fgcolor=rgb(170,170,170)
disallowbold=false
cursorblinks=false
cursorunderline=false
audiblebell=false
visualbell=false
tabpos=top
hidescrollbar=false
hidemenubar=true
hideclosebutton=true
hidepointer=false
disablef10=false
disablealt=false
disableconfirm=false
tabwidth=100
