#!/bin/bash

# This is, for information, the script used by vthierry to share his "like a RasPi" user configuration under Ubuntu

if [ "$USER" = vthierry ]
then 

  cd `dirname $0`/..
  pwd
  
  ## Creates the local configuration bundle
  mkdir -p {.config,.local/share,Desktop}
  cp -r /home/vthierry/sketchbook/home-on-RasPi/{.bashrc,bin} .
  cp -r /home/vthierry/.config/{dconf,menus} /home/vthierry/sketchbook/home-on-RasPi/.config/{lxterminal,pcmanfm,user-dirs.dirs} .config
  cp -r /home/vthierry/sketchbook/home-on-RasPi/.local/share/{applications,file-manager} .local/share
  git add .gitignore .bashrc bin .config .local
  bin/git_sync
  
  ## Mirrors in the test directory
  sudo su -c '/bin/rm -rf /home/tvievill/{.*,*}'
  sudo su -c 'cp -r {.gitignore,.bashrc,bin,.config,.local} /home/tvievill'
  sudo su -c 'chown -R tvievill /home/tvievill ; chgrp -R tvievill /home/tvievill '
  sudo su -c 'ls -Rla /home/tvievill/'
fi


