#!/bin/bash

confirm() {
  read -p "$1? (y/N) : " -n 1 -e rep ; if [ "$rep" = "y" ] ; then true ; else if [ \! -z "$exit_message" ] ; then echo -e "$exit_message" ; exit 1 ; fi ; false ; fi
}

# Usage: Installs a RasPi-like light environment on Ubuntu or other Linux distributions

if confirm "Install a RasPi-like light environment ?" "Ok, bye"
then
  ### 0/ Works in a temporary directory
  /bin/rm -rf /tmp/install*
  mkdir -p /tmp/install$$
  pushd /tmp/install$$ >/dev/null

  ### 1/ Installs mate if not yet done
  sudo apt install -qq -y ubuntu-mate-desktop wget
  sudo locale-gen ; sudo update-locale LANG=en_US.UTF-8 ##=> Defines here the locale language

  ### 2/ Installs the PiX theme
  theme=pix-theme_0.1_amd64 ##=> Most recent theme on 2026/09/29, may evolve.
  wget -q https://github.com/b1ack0p/pixflat-theme/raw/main/packages/pool/themes/$theme.deb
  dpkg-deb -R $theme.deb .
  sudo cp -r usr/share/themes/PiX /usr/share/themes
  /bin/rm -rf DEBIAN usr

  ### 3/ Installs PiX icons
  icons=pixtrix-icons_0.6_all+debcompat  ##=> Most recent icon set on 2026/09/29, may evolve.
  wget -q https://github.com/b1ack0p/pixflat-theme/raw/main/packages/pool/icons/$icons.deb
  dpkg-deb -R $icons.deb .
  sudo cp -r usr/share/icons/PiX* /usr/share/icons

  ### 00/ Cleans up
  popd >/dev/null
  /bin/rm -rf /tmp/install*
  echo "Please follow https://github.com/vthierry/like-a-RasPi/blob/main/README.md"
fi

if confirm "Install the home directory files ?" "Ok, bye"
then
  wget -q https://github.com/vthierry/like-a-RasPi/archive/refs/heads/main.zip
  unzip -o main.zip; rm main.zip
fi






