[*]
desktop_bg=#241F31
desktop_shadow=#241F31
desktop_fg=#E8E8E8
desktop_font=Nunito Sans Light 12
wallpaper=/usr/share/rpd-wallpaper/license.txt
wallpaper_mode=crop
show_home=0
show_trash=0
show_mounts=0
folder=/home/vthierry/Desktop
